fix: sonar token configuration

diff --git a/.github/workflows/continous-integration.yml b/.github/workflows/continous-integration.yml
--- a/.github/workflows/continous-integration.yml
+++ b/.github/workflows/continous-integration.yml
@@ -12,7 +12,8 @@ jobs:
     runs-on: ubuntu-24.04
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
 
       - name: Set up JDK 21
         uses: actions/setup-java@v4
@@ -21,14 +22,19 @@ jobs:
           java-version: 21
 
       - name: Maven tests
-        run: cd TP1/simple-api-student && mvn clean verify
+        run: |
+          cd TP1/simple-api-student
+          mvn clean verify
 
   sonar-analysis:
     needs: test-backend
     runs-on: ubuntu-24.04
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up JDK 21
         uses: actions/setup-java@v4
@@ -36,5 +42,16 @@ jobs:
           distribution: temurin
           java-version: 21
 
+      - name: Check SONAR_TOKEN
+        run: |
+          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
+            echo "SONAR_TOKEN is missing"
+            exit 1
+          else
+            echo "SONAR_TOKEN is present"
+          fi
+
       - name: SonarCloud analysis
-        run: cd TP1/simple-api-student && mvn -B verify sonar:sonar -Dsonar.projectKey=ENISSAY39_Dev_Ops_Gharbi_Yassine -Dsonar.organization=enissay39 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+        run: |
+          cd TP1/simple-api-student
+          mvn -B verify sonar:sonar -Dsonar.projectKey=ENISSAY39_Dev_Ops_Gharbi_Yassine -Dsonar.organization=enissay39 -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
